/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SiVeHogar;

import java.awt.Color;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    int xMouse, yMouse;
    private final String textoUsuario = "Ingrese su nombre de usuario";
    private final String textoContraseña = "**********" ;
    private final String compararAdmin = "Administrador";
    private final String IMAGEN = "/icon/Carrito.png";
    private final String TABLA = "Empleado";
    private boolean esAdmin = false;
    private int sesion = 0;
    DBManager dbManager = DBManager.getDBManager();
    Dashboard dashboard;
    
    public Login() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource(IMAGEN)).getImage());
         
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuariotxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        contrapwf = new javax.swing.JPasswordField();
        panelEntrar = new javax.swing.JPanel();
        txtEntrar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JPanel();
        txtCerra = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        barraArriba = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SiVeHogar/Imagenes/Cash Payment (1).gif"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 113, 206));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Desarrolladora Javamonos.Inc");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 440));

        jPanel3.setBackground(new java.awt.Color(0, 113, 206));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Iniciar Sesión");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 55, 440, -1));

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USUARIO");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 143, 91, -1));

        usuariotxt.setBackground(new java.awt.Color(0, 113, 206));
        usuariotxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuariotxt.setForeground(new java.awt.Color(204, 204, 204));
        usuariotxt.setText("Ingrese su nombre de usuario");
        usuariotxt.setBorder(null);
        usuariotxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuariotxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuariotxtFocusLost(evt);
            }
        });
        jPanel3.add(usuariotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 172, 250, 24));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 202, 276, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SiVeHogar/Imagenes/icons8_user_20px_1.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 172, -1, -1));

        jLabel6.setFont(new java.awt.Font("Garamond", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONTRASEÑA");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 238, 118, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SiVeHogar/Imagenes/bloquear.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 264, -1, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 286, 276, 10));

        contrapwf.setBackground(new java.awt.Color(0, 113, 206));
        contrapwf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contrapwf.setForeground(new java.awt.Color(204, 204, 204));
        contrapwf.setText("**********");
        contrapwf.setBorder(null);
        contrapwf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contrapwfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contrapwfFocusLost(evt);
            }
        });
        jPanel3.add(contrapwf, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 263, 200, -1));

        panelEntrar.setBackground(new java.awt.Color(4, 30, 66));

        txtEntrar.setBackground(new java.awt.Color(255, 255, 255));
        txtEntrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtEntrar.setForeground(new java.awt.Color(255, 255, 255));
        txtEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEntrar.setText("ENTRAR");
        txtEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEntrarLayout = new javax.swing.GroupLayout(panelEntrar);
        panelEntrar.setLayout(panelEntrarLayout);
        panelEntrarLayout.setHorizontalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        panelEntrarLayout.setVerticalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(panelEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 280, -1));

        btnCerrar.setBackground(new java.awt.Color(153, 51, 0));
        btnCerrar.setMinimumSize(new java.awt.Dimension(40, 40));
        btnCerrar.setPreferredSize(new java.awt.Dimension(40, 40));

        txtCerra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCerra.setForeground(new java.awt.Color(255, 255, 255));
        txtCerra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerra.setText("X");
        txtCerra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCerra.setMinimumSize(new java.awt.Dimension(40, 40));
        txtCerra.setPreferredSize(new java.awt.Dimension(40, 40));
        txtCerra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerraMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCerrarLayout = new javax.swing.GroupLayout(btnCerrar);
        btnCerrar.setLayout(btnCerrarLayout);
        btnCerrarLayout.setHorizontalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtCerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCerrarLayout.setVerticalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtCerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 0, 40, -1));

        disable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SiVeHogar/Imagenes/icons8_invisible_20px_1.png"))); // NOI18N
        disable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel3.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 40, 40));

        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SiVeHogar/Imagenes/icons8_eye_20px_1.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel3.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 40, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Hola, de nuevo. Tengamos un día agradable.");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 100, 440, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, 440));

        barraArriba.setBackground(new java.awt.Color(255, 255, 255));
        barraArriba.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barraArriba.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraArribaMouseDragged(evt);
            }
        });
        barraArriba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraArribaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barraArribaLayout = new javax.swing.GroupLayout(barraArriba);
        barraArriba.setLayout(barraArribaLayout);
        barraArribaLayout.setHorizontalGroup(
            barraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        barraArribaLayout.setVerticalGroup(
            barraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(barraArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraArribaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraArribaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraArribaMousePressed

    private void barraArribaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraArribaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraArribaMouseDragged

    private void txtCerraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerraMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtCerraMouseClicked

    private void txtCerraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerraMouseEntered
        btnCerrar.setBackground(Color.red);
    }//GEN-LAST:event_txtCerraMouseEntered

    private void txtCerraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerraMouseExited
        btnCerrar.setBackground(new Color(153,51,0));
    }//GEN-LAST:event_txtCerraMouseExited

    private void txtEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntrarMouseEntered
        panelEntrar.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_txtEntrarMouseEntered

    private void txtEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntrarMouseExited
        panelEntrar.setBackground(new Color(4,30,66));
    }//GEN-LAST:event_txtEntrarMouseExited

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        contrapwf.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void ocultarContraseña(){
        contrapwf.setEchoChar((char)42);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }
    
    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        ocultarContraseña();
    }//GEN-LAST:event_showMouseClicked

    private void usuariotxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuariotxtFocusGained
        if(usuariotxt.getText().equals(textoUsuario)){
            usuariotxt.setText("");
            usuariotxt.setForeground(Color.white);
        }
    }//GEN-LAST:event_usuariotxtFocusGained

    private void usuariotxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuariotxtFocusLost
        if(usuariotxt.getText().isEmpty()){
            usuariotxt.setText(textoUsuario);
            usuariotxt.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_usuariotxtFocusLost

    private void contrapwfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrapwfFocusGained
        if(String.valueOf(contrapwf.getPassword()).equals(textoContraseña)){
            contrapwf.setText("");
            contrapwf.setForeground(Color.white);    
        }
    }//GEN-LAST:event_contrapwfFocusGained

    private void contrapwfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrapwfFocusLost
        if(String.valueOf(contrapwf.getPassword()).isEmpty()){
            contrapwf.setText(textoContraseña);
            contrapwf.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_contrapwfFocusLost

    private void txtEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntrarMouseClicked
        if(usuariotxt.getText().equals(textoUsuario) || usuariotxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese un usuario.");
            return;
        }
        
        if( Arrays.equals(textoContraseña.toCharArray(), contrapwf.getPassword())  ||  contrapwf.getPassword().length==0 ){
            JOptionPane.showMessageDialog(this, "Ingrese su contraseña.");
            return;
        }
        
        
        
        if( esUsuario(usuariotxt.getText(), contrapwf.getPassword()) ){
            dashboard = new Dashboard(this,esAdmin,sesion);
            
            esAdmin = false;
            
            dashboard.setIconImage(new ImageIcon(getClass().getResource(IMAGEN)).getImage());
            dashboard.setVisible(true);
            dashboard.setLocationRelativeTo(null);
            
            usuariotxt.setText(textoUsuario);
            contrapwf.setText(textoContraseña);
            ocultarContraseña();
            
            this.dispose();
        }
    }//GEN-LAST:event_txtEntrarMouseClicked
    
    private boolean esUsuario(String usuario, char[] contra){

        Map<String,Object> where = new HashMap<>();
        where.put("usuario", usuario);
        
        Map<String,Object> datosUsuario  = dbManager.buscarUno(TABLA, where);
        if(datosUsuario.size() == 0){
            JOptionPane.showMessageDialog(this, "Usuario o contraseña invalidos.");
            return false;
        }
        sesion = Integer.parseInt(datosUsuario.get("idEmpleado").toString());
        if( !Arrays.equals(datosUsuario.get("contraseña").toString().toCharArray(), contra) ){
            JOptionPane.showMessageDialog(this, "Usuario o contraseña invalidos.");
            return false;
        }
        
        if(datosUsuario.get("puesto").equals(compararAdmin)){
            esAdmin = true;
        }
        
        return true; 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login login = new Login();
                login.setVisible(true);
                login.setLocationRelativeTo(null);
                login.requestFocus();
                /*
                DBManager dbManager = new DBManager();
                Map<String, Object> datos = new HashMap<>();
                
                datos.put("telefono","000000000000000" );
                datos.put("fechaNacimiento", "00/00/0000");
                datos.put("fechaIngreso", "00/00/0000");
                datos.put("puesto","administrador");
                datos.put("usuario", "admin");
                datos.put("contraseña", "admin");
                
                dbManager.insertar("Empleado", datos);
                datos.put("nombre", "prueba");
                datos.put("disponibles", 0);
                datos.put("precioBruto", 0);
                datos.put("precioNeto",0);
                datos.put("descripcion", "prueba");
                dbManager.insertar("Producto", datos);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraArriba;
    private javax.swing.JPanel btnCerrar;
    private javax.swing.JPasswordField contrapwf;
    private javax.swing.JLabel disable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelEntrar;
    private javax.swing.JLabel show;
    private javax.swing.JLabel txtCerra;
    private javax.swing.JLabel txtEntrar;
    private javax.swing.JTextField usuariotxt;
    // End of variables declaration//GEN-END:variables
}
