/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SiVeHogar;


import java.awt.Color;
import javax.swing.JPanel;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;


public class Productos extends javax.swing.JPanel {

    public static final String TABLA = "Producto";
    private static final String buscarTexto = "Ingrese el nombre del producto a buscar";
    
    private static final String[] datosTabla = new String [] {
        "Folio", "Nombre", "Disponibles", "Precio Bruto", "Precio Neto", "Descripción"
    }; 
    
    private static final String[] datosBD = new String [] {
        "idProducto", "nombre", "disponibles", "precioBruto","precioNeto","descripcion"
    };
    
    DBManager dbManager = DBManager.getDBManager();
    Dashboard parent;
    /**
     * Creates new form Principal
     */
    public Productos(Dashboard parent) {
        initComponents();
        actualizarTabla();
        usrnm.setText(buscarTexto);
        this.parent = parent;
    }
    
    public void actualizarTabla(){
        actualizarTabla(dbManager.listar(TABLA));
    }
    
    private void actualizarTabla(List<Map<String,Object>> datos){
        
        jTable1.setModel( new javax.swing.table.DefaultTableModel(datosTabla, 0));
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        for(Map<String,Object> producto: datos){
            Vector<String> fila = new Vector<>();
            for(String columna: datosBD){
                Object agregar = producto.get(columna);
                if(agregar == null){
                    fila.add("");
                }else{
                    fila.add(agregar.toString());
                }
            }
            model.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        usrnm = new javax.swing.JTextField();
        btnBuscarLibro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JPanel();
        labelAgregar = new javax.swing.JLabel();
        btnModificar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        eliminar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Productos");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 620, 10));

        usrnm.setForeground(new java.awt.Color(102, 102, 102));
        usrnm.setBorder(null);
        usrnm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usrnmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usrnmFocusLost(evt);
            }
        });
        add(usrnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 620, 30));

        btnBuscarLibro.setBackground(new java.awt.Color(4, 30, 66));
        btnBuscarLibro.setToolTipText("");
        btnBuscarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarLibroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarLibroMousePressed(evt);
            }
        });
        btnBuscarLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar");
        btnBuscarLibro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, -1));

        add(btnBuscarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 80, 30));

        btnAgregar.setBackground(new java.awt.Color(4, 30, 66));
        btnAgregar.setToolTipText("");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarMousePressed(evt);
            }
        });
        btnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelAgregar.setForeground(new java.awt.Color(255, 255, 255));
        labelAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAgregar.setText("Nuevo");
        btnAgregar.add(labelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, -1));

        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 80, -1));

        btnModificar.setBackground(new java.awt.Color(4, 30, 66));
        btnModificar.setToolTipText("");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModificarMousePressed(evt);
            }
        });
        btnModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificar");
        btnModificar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, -1));

        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 110, -1));

        eliminar.setBackground(new java.awt.Color(4, 30, 66));
        eliminar.setToolTipText("");
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarMousePressed(evt);
            }
        });
        eliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Eliminar");
        eliminar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, -1));

        add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 90, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 730, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMousePressed
        // Abrir sección
        parent.actualizarPantalla(new UpProductos(this));
    }//GEN-LAST:event_btnAgregarMousePressed

    private void eliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseEntered
        setColor(eliminar);
    }//GEN-LAST:event_eliminarMouseEntered

    private void eliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseExited
        resetColor(eliminar);
    }//GEN-LAST:event_eliminarMouseExited
    
    
    
    // BORRAR
    private void eliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMousePressed

        int idcell = jTable1.getSelectedRow();
        if (idcell <= -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un producto a borrar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            List<Map<String, Object>> datos = dbManager.listar(TABLA);
            String id = datos.get(idcell).get("idProducto").toString();

            int aceptar = javax.swing.JOptionPane.showConfirmDialog(this, "¿Desea eliminar este producto?", "ELIMINAR", javax.swing.JOptionPane.WARNING_MESSAGE);
            if (aceptar == javax.swing.JOptionPane.YES_OPTION) {
                Map<String, Object> where = new HashMap<>();
                where.put("idProducto", id);

                dbManager.eliminar(TABLA, where);
                javax.swing.JOptionPane.showMessageDialog(this, "¡Producto borrado! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_eliminarMousePressed

    // EDITAR
    private void btnModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMousePressed

        int idcell = jTable1.getSelectedRow();
        if (idcell <= -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el producto a editar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            List<Map<String, Object>> datos = dbManager.listar(TABLA);
            
            parent.actualizarPantalla(new UpProductos(this, datos.get(idcell)));
        }
    }//GEN-LAST:event_btnModificarMousePressed
    // BUSCAR
    private void btnBuscarLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarLibroMousePressed
        
        Map<String, Object> where = new HashMap<>();
        where.put("nombre", "%"+usrnm.getText()+"%");
        actualizarTabla( dbManager.listar(TABLA, where) );
        
    }//GEN-LAST:event_btnBuscarLibroMousePressed

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        setColor(btnAgregar);
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        resetColor(btnAgregar);
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnBuscarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarLibroMouseEntered
        setColor(btnBuscarLibro);
    }//GEN-LAST:event_btnBuscarLibroMouseEntered

    private void btnBuscarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarLibroMouseExited
        resetColor(btnBuscarLibro);
    }//GEN-LAST:event_btnBuscarLibroMouseExited

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered
        setColor(btnModificar);
    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
        resetColor(btnModificar);
    }//GEN-LAST:event_btnModificarMouseExited

    private void usrnmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usrnmFocusGained
        if(usrnm.getText().equals(buscarTexto))
            usrnm.setText("");
    }//GEN-LAST:event_usrnmFocusGained

    private void usrnmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usrnmFocusLost
        if(usrnm.getText().isEmpty())
            usrnm.setText(buscarTexto);
    }//GEN-LAST:event_usrnmFocusLost

    void setColor(JPanel panel){
        panel.setBackground(new Color(102,153,255));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(4,30,66));
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JPanel btnBuscarLibro;
    private javax.swing.JPanel btnModificar;
    private javax.swing.JPanel eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelAgregar;
    private javax.swing.JTextField usrnm;
    // End of variables declaration//GEN-END:variables
}
