/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SiVeHogar;

import java.awt.Color;
import javax.swing.JPanel;
import java.util.HashMap;
import java.util.Map;

public class UpClients extends javax.swing.JPanel {

    private boolean edition;
    private String origId;
    private javax.swing.JTextField[] campos;
    private static final String TABLA = Clientes.TABLA;
    public static final String[] datosBD = new String [] {
        "nombre", "apellidos", "direccion","telefono"
    };
    DBManager dbManager = DBManager.getDBManager();
    Clientes parent;
    private final String[] instrucciones = new String[]{
            "Ingrese el nombre",
            "Ingrese los apellidos",
            "Ingrese la dirección",
            "Ingrese el teléfono"
        };
    
    
    /**
     * Creates new form Principal
     */
    public UpClients(Clientes parent) {
        initComponents();
        this.parent = parent;
        edition = false;
        
        campos = new javax.swing.JTextField[]{
            nombreTextField,apellidosTextField,direccionTextField,telefonoTextField
                        };
        
        for(int i = 0; i<campos.length; i++){
            campos[i].setText(instrucciones[i]);
        }
        
    }
    
    public UpClients(Clientes parent,Map<String,Object> cliente){
        initComponents();
        this.parent = parent;
        edition = true;
        
        campos = new javax.swing.JTextField[]{
            nombreTextField,apellidosTextField,direccionTextField,telefonoTextField
                        };
        
        for (int i = 0; i < datosBD.length; i++) {
            Object agregar = cliente.get(datosBD[i]);
            if (agregar == null) {
                campos[i].setText("");
            } else {
                campos[i].setText(agregar.toString());
            }
        }
        
        origId = cliente.get("idCliente").toString();
        
        lblTitulo.setText("Actualizar nuevo cliente");
        jLabel1.setText("Guardar");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        apellidosTextField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        direccionTextField = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Text9 = new javax.swing.JLabel();
        telefonoTextField = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        button1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Agregar nuevo cliente");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 350));

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subir");
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 130, 50));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Nombre");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        nombreTextField.setForeground(new java.awt.Color(102, 102, 102));
        nombreTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreTextField.setBorder(null);
        nombreTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreTextFieldFocusLost(evt);
            }
        });
        add(nombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 310, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 310, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Apellidos");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        apellidosTextField.setForeground(new java.awt.Color(102, 102, 102));
        apellidosTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellidosTextField.setBorder(null);
        apellidosTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apellidosTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apellidosTextFieldFocusLost(evt);
            }
        });
        add(apellidosTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 310, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 310, 10));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Dirección");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        direccionTextField.setForeground(new java.awt.Color(102, 102, 102));
        direccionTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        direccionTextField.setBorder(null);
        direccionTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                direccionTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                direccionTextFieldFocusLost(evt);
            }
        });
        add(direccionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 310, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 310, 10));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Teléfono");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        telefonoTextField.setForeground(new java.awt.Color(102, 102, 102));
        telefonoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefonoTextField.setBorder(null);
        telefonoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoTextFieldFocusLost(evt);
            }
        });
        add(telefonoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 310, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 310, 10));

        button1.setBackground(new java.awt.Color(18, 90, 173));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
        });
        button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cancelar");
        button1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 130, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        setColor(button);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColor(button);
    }//GEN-LAST:event_buttonMouseExited

    // SUBIR
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        boolean algunDatoVacio = false;
        Map<String,Object> subir = new HashMap<>();
        
        for(int i = 0; i < campos.length; i++){
            subir.put(datosBD[i], campos[i].getText());
            
            if(campos[i].getText().equals(instrucciones[i])){
                algunDatoVacio = true;
                break;
            }
        }
        
        if(algunDatoVacio){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }else{
            String errores = "";
            if( !nombreTextField.getText().matches("^[a-zA-Z\\s]+$") ){
                errores += "ERROR curp invalido\n";
            }
            if( !apellidosTextField.getText().matches("^[a-zA-Z\\s]+$") ){
                errores += "ERROR nombre debe ser alfabetico\n";
            }
            if( !telefonoTextField.getText().matches("^\\d+$") ){
                errores += "ERROR correo invalida\n";
            }

            
            if (errores.length() > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, errores, "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (edition) {
                    Map<String, Object> where = new HashMap<>();
                    where.put("idCliente", origId);

                    dbManager.actualizar(TABLA, subir, where);
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "¡Cliente editado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                } else {
                    dbManager.insertar(TABLA, subir);
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "¡Cliente registrado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
                
                parent.parent.actualizarPantalla(parent);
                parent.actualizarTabla();
            }
        }
    }//GEN-LAST:event_buttonMousePressed

    private void nombreTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTextFieldFocusGained
        if(campos[0].getText().equals(instrucciones[0])){
            campos[0].setText("");
        }
    }//GEN-LAST:event_nombreTextFieldFocusGained

    private void nombreTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTextFieldFocusLost
        if(campos[0].getText().isEmpty()){
            campos[0].setText(instrucciones[0]);
        }
    }//GEN-LAST:event_nombreTextFieldFocusLost

    private void apellidosTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidosTextFieldFocusGained
        if(campos[1].getText().equals(instrucciones[1])){
            campos[1].setText("");
        }
    }//GEN-LAST:event_apellidosTextFieldFocusGained

    private void apellidosTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidosTextFieldFocusLost
        if(campos[1].getText().isEmpty()){
            campos[1].setText(instrucciones[1]);
        }
    }//GEN-LAST:event_apellidosTextFieldFocusLost

    private void direccionTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTextFieldFocusGained
        if(campos[2].getText().equals(instrucciones[2])){
            campos[2].setText("");
        }
    }//GEN-LAST:event_direccionTextFieldFocusGained

    private void direccionTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTextFieldFocusLost
        if(campos[2].getText().isEmpty()){
            campos[2].setText(instrucciones[2]);
        }
    }//GEN-LAST:event_direccionTextFieldFocusLost

    private void telefonoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoTextFieldFocusLost
        if(campos[3].getText().isEmpty()){
            campos[3].setText(instrucciones[3]);
        }
    }//GEN-LAST:event_telefonoTextFieldFocusLost

    private void telefonoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoTextFieldFocusGained
        if(campos[3].getText().equals(instrucciones[3])){
            campos[3].setText("");
        }
    }//GEN-LAST:event_telefonoTextFieldFocusGained

    private void button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseEntered
        setColor(button1);
    }//GEN-LAST:event_button1MouseEntered

    private void button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseExited
        resetColor(button1);
    }//GEN-LAST:event_button1MouseExited

    private void button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MousePressed
        parent.parent.actualizarPantalla(parent);
    }//GEN-LAST:event_button1MousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text9;
    private javax.swing.JTextField apellidosTextField;
    private javax.swing.JPanel body;
    private javax.swing.JPanel button;
    private javax.swing.JPanel button1;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField telefonoTextField;
    // End of variables declaration//GEN-END:variables
}
