/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SiVeHogar;

import java.awt.Color;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class Vender extends javax.swing.JPanel {
    
    private static final DecimalFormat df = new DecimalFormat("0.00");  
    DBManager dbManager = DBManager.getDBManager();
    private final String TABLA_PRODUCTO = "Producto";
    private final String TABLA_CLIENTE = "Cliente";
    private final String TABLA_EMPLEADO = "Empleado";
    private final String TABLA_CARRITO = "Carrito";
    private final String TABLA_VENTAS = "Venta";
    
    private double total;
    private double subtotal;
    
    private String pattern = "dd-MM-yyyy";
    private SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
    Dashboard parent;
    
    private List<Map<String,Object>> listaProductos;
    
    /**
     * Creates new form Principal
     */
    public Vender(Dashboard parent) {
        total = 0;
        subtotal = 0;
        initComponents();
        listaProductos = new ArrayList<>();
        this.parent = parent;
        datosEmpleado();
        noVenta();
        fechaTextField.setText(simpleDateFormat.format(new Date()));
        
        codigoProductoTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                actualizarProducto();
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                actualizarProducto();
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                actualizarProducto();
            }
        });
        
        cantidadProductoTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                actualizarPrecio();
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                actualizarPrecio();
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                actualizarPrecio();
            }
        });
        
        nOClienteTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                actualizarCliente();
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                actualizarCliente();
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                actualizarCliente();
            }
        });
        
        pagoTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                actualizarCambio();
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                actualizarCambio();
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                actualizarCambio();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        fechaTextField = new javax.swing.JTextField();
        nuevoProductoButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nOPersonalEmpleadoTextField = new javax.swing.JTextField();
        Text3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        nombreEmpleadoTextField = new javax.swing.JTextField();
        Text4 = new javax.swing.JLabel();
        Text5 = new javax.swing.JLabel();
        Text6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        apellidosEmpleadoTextField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        nOClienteTextField = new javax.swing.JTextField();
        Text7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        nombreClienteTextField = new javax.swing.JTextField();
        Text8 = new javax.swing.JLabel();
        Text9 = new javax.swing.JLabel();
        Text10 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        apellidosClienteTextField = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        codigoProductoTextField = new javax.swing.JTextField();
        Text11 = new javax.swing.JLabel();
        Text12 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        nombreProductoTextField = new javax.swing.JTextField();
        Text13 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        cantidadProductoTextField = new javax.swing.JTextField();
        Text14 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        descripcionProductoTextField = new javax.swing.JTextField();
        Text15 = new javax.swing.JLabel();
        Text16 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        precioProductoTextField = new javax.swing.JTextField();
        Text17 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        cantidadXproductoTextField = new javax.swing.JTextField();
        Text18 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        subtotalTextField = new javax.swing.JTextField();
        Text19 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        totalTextField = new javax.swing.JTextField();
        Text20 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        pagoTextField = new javax.swing.JTextField();
        Text21 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        cambioTextField = new javax.swing.JTextField();
        finVentaButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cancelarVentaButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Text22 = new javax.swing.JLabel();
        noVentaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Nueva Venta");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 730, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Fecha");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 10));

        fechaTextField.setEditable(false);
        fechaTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        fechaTextField.setForeground(new java.awt.Color(102, 102, 102));
        fechaTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fechaTextField.setEnabled(false);
        add(fechaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 100, 30));

        nuevoProductoButton.setBackground(new java.awt.Color(18, 90, 173));
        nuevoProductoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nuevoProductoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoProductoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoProductoButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nuevoProductoButtonMousePressed(evt);
            }
        });
        nuevoProductoButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo producto");
        nuevoProductoButton.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        add(nuevoProductoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 150, 30));

        nOPersonalEmpleadoTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nOPersonalEmpleadoTextField.setForeground(new java.awt.Color(102, 102, 102));
        nOPersonalEmpleadoTextField.setBorder(null);
        nOPersonalEmpleadoTextField.setEnabled(false);
        add(nOPersonalEmpleadoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, 30));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Nombre");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, 10));

        nombreEmpleadoTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreEmpleadoTextField.setForeground(new java.awt.Color(102, 102, 102));
        nombreEmpleadoTextField.setBorder(null);
        nombreEmpleadoTextField.setEnabled(false);
        add(nombreEmpleadoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, 30));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("# Personal");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        Text5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Text5.setText("Empleado");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Apellidos");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 240, 10));

        apellidosEmpleadoTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        apellidosEmpleadoTextField.setForeground(new java.awt.Color(102, 102, 102));
        apellidosEmpleadoTextField.setBorder(null);
        apellidosEmpleadoTextField.setEnabled(false);
        add(apellidosEmpleadoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 240, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, 10));

        nOClienteTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nOClienteTextField.setForeground(new java.awt.Color(102, 102, 102));
        nOClienteTextField.setBorder(null);
        add(nOClienteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 30));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Nombre");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 150, 10));

        nombreClienteTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreClienteTextField.setForeground(new java.awt.Color(102, 102, 102));
        nombreClienteTextField.setBorder(null);
        nombreClienteTextField.setEnabled(false);
        add(nombreClienteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 150, 30));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("# Cliente");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        Text9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Text9.setText("Cliente");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        Text10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text10.setText("Apellidos");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 240, 10));

        apellidosClienteTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        apellidosClienteTextField.setForeground(new java.awt.Color(102, 102, 102));
        apellidosClienteTextField.setBorder(null);
        apellidosClienteTextField.setEnabled(false);
        add(apellidosClienteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 240, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, 10));

        codigoProductoTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        codigoProductoTextField.setForeground(new java.awt.Color(102, 102, 102));
        codigoProductoTextField.setBorder(null);
        add(codigoProductoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 30));

        Text11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text11.setText("Código");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        Text12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Text12.setText("Productos");
        add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 170, 10));

        nombreProductoTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreProductoTextField.setForeground(new java.awt.Color(102, 102, 102));
        nombreProductoTextField.setBorder(null);
        nombreProductoTextField.setEnabled(false);
        add(nombreProductoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 170, 30));

        Text13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text13.setText("Nombre");
        add(Text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 150, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 50, 10));

        cantidadProductoTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cantidadProductoTextField.setForeground(new java.awt.Color(102, 102, 102));
        cantidadProductoTextField.setBorder(null);
        add(cantidadProductoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 50, 30));

        Text14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text14.setText("Subtotal");
        add(Text14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 60, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator11.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 170, 10));

        descripcionProductoTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        descripcionProductoTextField.setForeground(new java.awt.Color(102, 102, 102));
        descripcionProductoTextField.setBorder(null);
        descripcionProductoTextField.setEnabled(false);
        add(descripcionProductoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 170, 30));

        Text15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text15.setText("Descripción");
        add(Text15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 150, -1));

        Text16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text16.setText("Cantidad");
        add(Text16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 100, -1));

        jSeparator13.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator13.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 60, 10));

        precioProductoTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        precioProductoTextField.setForeground(new java.awt.Color(102, 102, 102));
        precioProductoTextField.setBorder(null);
        precioProductoTextField.setEnabled(false);
        add(precioProductoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 60, 30));

        Text17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text17.setText("Precio");
        add(Text17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 50, -1));

        jSeparator14.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator14.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 100, 10));

        cantidadXproductoTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cantidadXproductoTextField.setForeground(new java.awt.Color(102, 102, 102));
        cantidadXproductoTextField.setBorder(null);
        cantidadXproductoTextField.setEnabled(false);
        add(cantidadXproductoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 100, 30));

        Text18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text18.setText("Cantidad");
        add(Text18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 70, -1));

        jSeparator15.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator15.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 100, 10));

        subtotalTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        subtotalTextField.setForeground(new java.awt.Color(102, 102, 102));
        subtotalTextField.setText("0.0");
        subtotalTextField.setBorder(null);
        subtotalTextField.setEnabled(false);
        add(subtotalTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 100, 30));

        Text19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text19.setText("Total");
        add(Text19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 40, -1));

        jSeparator16.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator16.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 100, 10));

        totalTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        totalTextField.setForeground(new java.awt.Color(102, 102, 102));
        totalTextField.setText("0.0");
        totalTextField.setBorder(null);
        totalTextField.setEnabled(false);
        add(totalTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 100, 30));

        Text20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text20.setText("Pago");
        add(Text20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 40, 30));

        jSeparator17.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator17.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 100, 10));

        pagoTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pagoTextField.setForeground(new java.awt.Color(102, 102, 102));
        pagoTextField.setBorder(null);
        add(pagoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 100, 30));

        Text21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text21.setText("Cambio");
        add(Text21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 50, 30));

        jSeparator18.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator18.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 100, 10));

        cambioTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cambioTextField.setForeground(new java.awt.Color(102, 102, 102));
        cambioTextField.setBorder(null);
        cambioTextField.setEnabled(false);
        add(cambioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 100, 30));

        finVentaButton.setBackground(new java.awt.Color(18, 90, 173));
        finVentaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        finVentaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                finVentaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                finVentaButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                finVentaButtonMousePressed(evt);
            }
        });
        finVentaButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fin de venta");
        finVentaButton.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        add(finVentaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        cancelarVentaButton.setBackground(new java.awt.Color(18, 90, 173));
        cancelarVentaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelarVentaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarVentaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarVentaButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarVentaButtonMousePressed(evt);
            }
        });
        cancelarVentaButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cancelar venta");
        cancelarVentaButton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        add(cancelarVentaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        Text22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text22.setText("#Venta");
        add(Text22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, 30));

        noVentaTextField.setEditable(false);
        noVentaTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        noVentaTextField.setForeground(new java.awt.Color(102, 102, 102));
        noVentaTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        noVentaTextField.setEnabled(false);
        add(noVentaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 50, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("XProducto");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 210, 90, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    private void datosEmpleado(){
        Map<String,Object> where = new HashMap<>();
        where.put("idEmpleado", parent.getSesion());
        Map<String,Object> empleado = dbManager.buscarUno(TABLA_EMPLEADO, where);
        System.out.println(empleado);
        nOPersonalEmpleadoTextField.setText(parent.getSesion()+"");
        Object nombre = empleado.get("nombre");
        if(nombre != null)
            nombreEmpleadoTextField.setText(nombre.toString());
        Object apellido = empleado.get("apellidos");
        if(apellido != null)
            apellidosEmpleadoTextField.setText(apellido.toString());
        
    }
    
    private void noVenta(){
        List<Map<String,Object>> ventas = dbManager.listar(TABLA_VENTAS);
        if(ventas.size()==0){
            noVentaTextField.setText("1");
        }else{
            Object ventaString = ventas.get(ventas.size()-1).get("folioVenta");
            
            int venta = Integer.parseInt(ventaString.toString());
            noVentaTextField.setText((venta+1)+"");
        }
        
    }
    
    private void actualizarCambio() {
        String pago = pagoTextField.getText();
        String total = totalTextField.getText();
        if ((pago.matches("\\d+\\.\\d+") || pago.matches("^\\d+$") )&& (total.matches("\\d+\\.\\d+") || total.matches("^\\d+$"))) {
            double cambio = Double.parseDouble(pago)
                    - Double.parseDouble(total);
            cambioTextField.setText((cambio<0)?"Falta dinero":df.format(cambio));
        } else {
            cambioTextField.setText("");
        }
    }
    
    private void actualizarProducto() {
        Map<String, Object> where = new HashMap<>();
        where.put("idProducto", codigoProductoTextField.getText());
        
        cantidadProductoTextField.setText("");
        cantidadXproductoTextField.setText("");
        
        Map<String, Object> datosProducto = dbManager.buscarUno(TABLA_PRODUCTO, where);
        if (datosProducto.size() != 0) {
            nombreProductoTextField.setText(datosProducto.get("nombre").toString());
            descripcionProductoTextField.setText(datosProducto.get("descripcion").toString());
            precioProductoTextField.setText(datosProducto.get("precioBruto").toString());
        }else{
            nombreProductoTextField.setText("");
            descripcionProductoTextField.setText("");
            precioProductoTextField.setText("");
        }
    }
    
    private void actualizarCliente() {
        Map<String, Object> where = new HashMap<>();
        where.put("idCliente", nOClienteTextField.getText());

        Map<String, Object> datosCliente = dbManager.buscarUno(TABLA_CLIENTE, where);
        if (datosCliente.size() != 0) {
            nombreClienteTextField.setText(datosCliente.get("nombre").toString());
            apellidosClienteTextField.setText(datosCliente.get("apellidos").toString());
        } else {
            nombreClienteTextField.setText("");
            apellidosClienteTextField.setText("");
        }
    }
    
    private void actualizarPrecio(){
        Map<String, Object> where = new HashMap<>();
        where.put("idProducto", codigoProductoTextField.getText());
        Map<String, Object> datosProducto = dbManager.buscarUno(TABLA_PRODUCTO, where);
        
        String cantidad = cantidadProductoTextField.getText();
        String precio = precioProductoTextField.getText();
        
        subtotalTextField.setText(subtotal + "");
        totalTextField.setText(total + "");

        if (cantidad.matches("^\\d+$") && precio.matches("\\d+\\.\\d+")) {
            if (Integer.parseInt(cantidad) <= Integer.parseInt(datosProducto.get("disponibles").toString())) {
                cantidadXproductoTextField.setText(df.format(
                        Integer.parseInt(cantidad)
                        * Double.parseDouble(precio)) );

                subtotalTextField.setText(df.format(
                        Double.parseDouble(subtotalTextField.getText())
                        + Double.parseDouble(cantidadXproductoTextField.getText())) );
                try {
                    double precioNeto = Double.parseDouble(datosProducto.get("precioNeto").toString());
                    totalTextField.setText(df.format(
                            Double.parseDouble(totalTextField.getText())
                            + (Double.parseDouble(cantidad) * precioNeto)) );
                } catch (Exception e) {}
            } else {
                cantidadXproductoTextField.setText("Insuficiente");
            }
        } else {
            cantidadXproductoTextField.setText("");
        }
        actualizarCambio();
    }
    
    private void agregarProductoLista(){
        
        total = Double.parseDouble( totalTextField.getText() ) ;
        subtotal = Double.parseDouble( subtotalTextField.getText() );
        
        Map<String,Object> producto = new HashMap<>();
        producto.put("producto", codigoProductoTextField.getText());
        producto.put("cantidad", cantidadProductoTextField.getText());
        producto.put("venta", noVentaTextField.getText());
        
        listaProductos.add(producto);
        codigoProductoTextField.setText("");
        codigoProductoTextField.requestFocus();
    }
    
    private void nuevoProductoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoProductoButtonMouseEntered
        setColor(nuevoProductoButton);
    }//GEN-LAST:event_nuevoProductoButtonMouseEntered

    private void nuevoProductoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoProductoButtonMouseExited
        resetColor(nuevoProductoButton);
    }//GEN-LAST:event_nuevoProductoButtonMouseExited
    
    private void nuevoProductoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoProductoButtonMousePressed
        
        agregarProductoLista();
        
    }//GEN-LAST:event_nuevoProductoButtonMousePressed

    private void finVentaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finVentaButtonMouseEntered
        setColor(finVentaButton);
    }//GEN-LAST:event_finVentaButtonMouseEntered

    private void finVentaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finVentaButtonMouseExited
        resetColor(finVentaButton);
    }//GEN-LAST:event_finVentaButtonMouseExited

    private void cancelarVentaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarVentaButtonMouseEntered
        setColor(cancelarVentaButton);
    }//GEN-LAST:event_cancelarVentaButtonMouseEntered

    private void cancelarVentaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarVentaButtonMouseExited
        resetColor(cancelarVentaButton);
    }//GEN-LAST:event_cancelarVentaButtonMouseExited

    private void cancelarVentaButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarVentaButtonMousePressed
        vaciarCamposYLista();
    }//GEN-LAST:event_cancelarVentaButtonMousePressed
    
    private void vaciarCamposYLista(){
        codigoProductoTextField.setText("");
        nOClienteTextField.setText("");
        
        total = 0;
        subtotal = 0;
        actualizarPrecio();
        
        cambioTextField.setText("");
        pagoTextField.setText("");
        
        listaProductos = new ArrayList<>();
    }
    
    private void finVentaButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finVentaButtonMousePressed
        if( cantidadProductoTextField.getText().isEmpty() || Integer.parseInt(cantidadProductoTextField.getText())<=0){
            javax.swing.JOptionPane.showConfirmDialog(this, "Ingrese la cantidad deseada", "ERROR", javax.swing.JOptionPane.PLAIN_MESSAGE);
            return;
        }
        
        if ( ! (pagoTextField.getText().matches("\\d+\\.\\d+")||pagoTextField.getText().matches("^\\d+$")) ){
            javax.swing.JOptionPane.showConfirmDialog(this, "Ingrese un pago", "ERROR", javax.swing.JOptionPane.PLAIN_MESSAGE);
            return;
        }
        if ( total > Integer.parseInt(pagoTextField.getText())) {
            javax.swing.JOptionPane.showConfirmDialog(this, "Pago insuficiente", "ERROR", javax.swing.JOptionPane.PLAIN_MESSAGE);
            return;
        }
        
        agregarProductoLista();

        Map<String, Object> venta = new HashMap<>();
        venta.put("total", total);
        venta.put("cambio", Double.parseDouble(cambioTextField.getText()));
        venta.put("empleado", Integer.parseInt(nOPersonalEmpleadoTextField.getText()));
        venta.put("fecha", fechaTextField.getText());
        if (!nombreClienteTextField.getText().isEmpty()) {
            venta.put("cliente", Integer.parseInt(nOClienteTextField.getText()));
        }
        
        dbManager.insertar(TABLA_VENTAS, venta);
        for (Map<String, Object> producto : listaProductos) {
            
            dbManager.insertar(TABLA_CARRITO, producto);
            
            Map<String, Object> whereID = new HashMap<>();
            whereID.put("idProducto", producto.get("producto"));
            
            Map<String, Object> bdProducto = dbManager.buscarUno(TABLA_PRODUCTO, whereID);
            int cambiarDisponibles = Integer.parseInt( bdProducto.get("disponibles").toString() );
            
            Map<String, Object> diferenciaProducto = new HashMap<>();
            diferenciaProducto.put("disponibles", cambiarDisponibles - Integer.parseInt( producto.get("cantidad").toString() ));
            
            dbManager.actualizar(TABLA_PRODUCTO, diferenciaProducto, whereID );
        }
        
        vaciarCamposYLista();
        nOClienteTextField.setText("");
        
        noVenta();
        javax.swing.JOptionPane.showConfirmDialog(this, "Venta realizada con exito.", "Venta", javax.swing.JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_finVentaButtonMousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text13;
    private javax.swing.JLabel Text14;
    private javax.swing.JLabel Text15;
    private javax.swing.JLabel Text16;
    private javax.swing.JLabel Text17;
    private javax.swing.JLabel Text18;
    private javax.swing.JLabel Text19;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text20;
    private javax.swing.JLabel Text21;
    private javax.swing.JLabel Text22;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField apellidosClienteTextField;
    private javax.swing.JTextField apellidosEmpleadoTextField;
    private javax.swing.JPanel body;
    private javax.swing.JTextField cambioTextField;
    private javax.swing.JPanel cancelarVentaButton;
    private javax.swing.JTextField cantidadProductoTextField;
    private javax.swing.JTextField cantidadXproductoTextField;
    private javax.swing.JTextField codigoProductoTextField;
    private javax.swing.JTextField descripcionProductoTextField;
    private javax.swing.JTextField fechaTextField;
    private javax.swing.JPanel finVentaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField nOClienteTextField;
    private javax.swing.JTextField nOPersonalEmpleadoTextField;
    private javax.swing.JTextField noVentaTextField;
    private javax.swing.JTextField nombreClienteTextField;
    private javax.swing.JTextField nombreEmpleadoTextField;
    private javax.swing.JTextField nombreProductoTextField;
    private javax.swing.JPanel nuevoProductoButton;
    private javax.swing.JTextField pagoTextField;
    private javax.swing.JTextField precioProductoTextField;
    private javax.swing.JTextField subtotalTextField;
    private javax.swing.JTextField totalTextField;
    // End of variables declaration//GEN-END:variables
}
