/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SiVeHogar;

import java.awt.Color;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    private final String TABLA = "Venta";
    private final String[] datosTabla = new String [] {
        "Folio", "Fecha", "Cliente", "Total", "Cambio"
    };
    private static final String[] datosBD = new String [] {
        "folioVenta", "fecha", "cliente", "total", "cambio"
    };
    DBManager dbManager = DBManager.getDBManager();
    Dashboard parent;
    
    private final String mensajeBusqueda = "Ingrese la fecha a buscar";
    
    public Ventas(Dashboard parent) {
        initComponents();
        this.parent = parent;
        usrnm.setText(mensajeBusqueda);
        actualizarTabla(dbManager.listar(TABLA));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        usrnm = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        search = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Ventas");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 750, 320));

        usrnm.setForeground(new java.awt.Color(102, 102, 102));
        usrnm.setBorder(null);
        usrnm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usrnmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usrnmFocusLost(evt);
            }
        });
        add(usrnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 620, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 620, 10));

        search.setBackground(new java.awt.Color(4, 30, 66));
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });
        search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Buscar");
        search.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, -1));

        add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 80, 30));
    }// </editor-fold>//GEN-END:initComponents
    
     private void actualizarTabla(List<Map<String,Object>> datos){
        
        jTable1.setModel( new javax.swing.table.DefaultTableModel(datosTabla, 0));
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        for(Map<String,Object> producto: datos){
            Vector<String> fila = new Vector<>();
            for(String columna: datosBD){
                Object agregar = producto.get(columna);
                if(agregar == null){
                    fila.add("");
                }else{
                    fila.add(agregar.toString());
                }
            }
            model.addRow(fila);
        }
    }
    
    private void usrnmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usrnmFocusGained
        if(usrnm.getText().equals(mensajeBusqueda))
        usrnm.setText("");
    }//GEN-LAST:event_usrnmFocusGained

    private void usrnmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usrnmFocusLost
        if(usrnm.getText().isEmpty())
        usrnm.setText(mensajeBusqueda);
    }//GEN-LAST:event_usrnmFocusLost

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        setColor(search);
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        resetColor(search);
    }//GEN-LAST:event_searchMouseExited

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed

        Map<String, Object> where = new HashMap<>();
        where.put("fecha", "%"+usrnm.getText()+"%");
        actualizarTabla( dbManager.listar(TABLA, where) );
    }//GEN-LAST:event_searchMousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(102,153,255));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(4,30,66));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel search;
    private javax.swing.JTextField usrnm;
    // End of variables declaration//GEN-END:variables
}
